
  name: movie_search_app
  description: A Flutter movie search app using the OMDb API.
  version: 1.0.0
  publish_to: 'none'

  environment:
    sdk: '>=3.0.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    provider: ^6.1.2
    http: ^1.2.2
    cupertino_icons: ^1.0.8

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true
