import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

import 'model.dart';

class MovieProvider with ChangeNotifier {
  List<Autogenerated> _movies = [];
  bool _isLoading = false;
  String? _errorMessage;

  List<Autogenerated> get movies => _movies;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  Future<void> searchMovies(String query) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final response = await http.get(
        Uri.parse('http://www.omdbapi.com/?s=$query&apikey=f756be78'),
      );

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        if (data['Response'] == 'True') {
          _movies = (data['Search'] as List)
              .map((movie) => Autogenerated.fromJson(movie))
              .toList();
        } else {
          _movies = [];
          _errorMessage = 'No movies found';
        }
      } else {
        _errorMessage = 'Error fetching data';
      }
    } catch (e) {
      _errorMessage = 'Error fetching data: $e';
    }

    _isLoading = false;
    notifyListeners();
  }
}