import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

import 'model.dart';

class MovieListItem extends StatelessWidget {
  final Autogenerated movie;

  const MovieListItem({super.key, required this.movie});

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      child: ListTile(
        leading: movie.poster != null && movie.poster != 'N/A'
            ? Image.network(
          movie.poster!,
          width: 50,
          height: 75,
          fit: BoxFit.cover,
          errorBuilder: (context, error, stackTrace) =>
          const Icon(Icons.movie),
        )
            : const Icon(Icons.movie),
        title: Text(
          movie.title ?? 'Unknown Title',
          style: const TextStyle(fontWeight: FontWeight.bold),
        ),
        subtitle: Text(movie.year ?? ''),
        onTap: () async {
          final response = await http.get(
            Uri.parse(
                'http://www.omdbapi.com/?i=${movie.imdbID}&apikey=f756be78'),
          );
          if (response.statusCode == 200) {
            final detailedMovie =
            Autogenerated.fromJson(json.decode(response.body));
            Navigator.pushNamed(
              context,
              '/details',
              arguments: detailedMovie,
            );
          }
        },
      ),
    );
  }
}